---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    deployment_name: QA
  register: openstack_servers

- name: output result
  debug:
    var: openstack_servers
    
- name: Delete instances
  os_server:
    name: "{{ servername }}"
    state: absent
  loop:
    - frontend
    - app1
    - app2
    - db
