---
# tasks file for lb-tier
- name: install frontend packages 
  package:
     name: "{{ frontend_packages }}" 
     state: present
  notify:
     - restart_haproxy
           
- name: enable haproxy
  service:
    name: haproxy
    state: started

- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart_haproxy
