- name: Create Homework Assignment project 
  command: |
    tower-cli project create --organization="{{org_name}}" --scm-type=git --scm-branch="{{scm_branch}}" --scm-url="{{ scm_url }}" --scm-update-on-launch=True -n "{{ project_name }}"

# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml

- name: Create credential to connect to workstation
  command: |
    tower-cli credential create --name "{{machine_credential_name}}" --organization "{{org_name}}" --credential-type Machine 

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Add workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Create tower credential key file
  tower_credential:
    name: Connect_to_workstation
    organization: {{org_name}}
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    ssh_key_data: "{{ lookup('file', '/root/.ssh/openstack.pem') }}" 
    username: cloud-user

- name: Remove secret.pem
  file:
    name: /root/secret.pem
    state: absent

